# RBE/CS549 Fall 2022: Computer Vision
## Homework 0: Alohomora

Author(s): 
Prof. Nitin J. Sanket (nsanket@wpi.edu), Lening Li (lli4@wpi.edu), Gejji, Vaishnavi Vivek (vgejji@wpi.edu)

Robotics Engineering Department,

Worcester Polytechnic Institute

Code adapted from CMSC733 at the University of Maryland, College Park.

## Phase 2

### Neural Network Construction

In [12]:
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

def accuracy(outputs, labels):
    _, preds = torch.max(outputs, dim=1)
    return torch.tensor(torch.sum(preds == labels).item() / len(preds))

def loss_fn(out, labels):
    ###############################################
    # Fill your loss function of choice here!
    ###############################################
    loss = nn.CrossEntropyLoss()
    loss = loss(out, labels)
    return loss

class ImageClassificationBase(nn.Module):
    def training_step(self, batch):
        images, labels = batch 
        out = self(images)                  # Generate predictions
        loss = loss_fn(out, labels) # Calculate loss
        return loss
    
    def validation_step(self, batch):
        images, labels = batch 
        out = self(images)                    # Generate predictions
        loss = loss_fn(out, labels)   # Calculate loss
        acc = accuracy(out, labels)           # Calculate accuracy
        return {'loss': loss.detach(), 'acc': acc}
        
    def validation_epoch_end(self, outputs):
        batch_losses = [x['loss'] for x in outputs]
        epoch_loss = torch.stack(batch_losses).mean()   # Combine losses
        batch_accs = [x['acc'] for x in outputs]
        epoch_acc = torch.stack(batch_accs).mean()      # Combine accuracies
        return {'loss': epoch_loss.item(), 'acc': epoch_acc.item()}
    
    def epoch_end(self, epoch, result):
        print("Epoch [{}], loss: {:.4f}, acc: {:.4f}".format(epoch, result['loss'], result['acc']))



class CIFAR10Model(ImageClassificationBase):
    def __init__(self, InputSize, OutputSize):
        """
        Inputs: 
        InputSize - Size of the Input
        OutputSize - Size of the Output
        """
        #############################
        # Fill your network initialization of choice here!
        #############################
        super().__init__()
        self.linear1 = nn.Linear(InputSize, 1024)
        self.linear2 = nn.Linear(1024, 512)
        self.linear3 = nn.Linear(512, 64)
        self.linear4 = nn.Linear(64, 64)
        self.linear5 = nn.Linear(64, OutputSize)

    def forward(self, xb):
        """
        Input:
        xb is a MiniBatch of the current image
        Outputs:
        out - output of the network
        """
        #############################
        # Fill your network structure of choice here!
        #############################
        out = xb.view(xb.size(0), -1)
        out = self.linear1(out)
        out = F.relu(out)
        out = self.linear2(out)
        out = F.relu(out)
        out = self.linear3(out)
        out = F.relu(out)
        out = self.linear4(out)
        out = F.relu(out)
        out = self.linear5(out)
        return out


In [13]:
import time
import glob
import os
import sys
import matplotlib.pyplot as plt
import numpy as np

def tic():
    """
    Function to start timer
    Tries to mimic tic() toc() in MATLAB
    """
    StartTime = time.time()
    return StartTime

def toc(StartTime):
    """
    Function to stop timer
    Tries to mimic tic() toc() in MATLAB
    """
    return time.time() - StartTime

def FindLatestModel(CheckPointPath):
    """
    Finds Latest Model in CheckPointPath
    Inputs:
    CheckPointPath - Path where you have stored checkpoints
    Outputs:
    LatestFile - File Name of the latest checkpoint
    """
    FileList = glob.glob(CheckPointPath + '*.ckpt.index') # * means all if need specific format then *.csv
    LatestFile = max(FileList, key=os.path.getctime)
    # Strip everything else except needed information
    LatestFile = LatestFile.replace(CheckPointPath, '')
    LatestFile = LatestFile.replace('.ckpt.index', '')
    return LatestFile


def convertToOneHot(vector, NumClasses):
    """
    Inputs:
    vector - vector of argmax indexes
    NumClasses - Number of classes
    """
    return np.equal.outer(vector, np.arange(NumClasses)).astype(np.float)

### Train your neural network

In [14]:
# # calculating 3 channel mean and std for image dataset
# import tqdm
# import random

# means = np.array([0, 0, 0], dtype=np.float32)
# stds = np.array([0, 0, 0], dtype=np.float32)
# total_images = 0
# randomly_sample = 5000
# for f in tqdm.tqdm(random.sample(glob.glob("dataset_path/**.jpg", recursive = True), randomly_sample)):
#     img = cv2.imread(f)
#     means += img.mean(axis=(0,1))
#     stds += img.std(axis=(0,1))
#     total_images += 1
# means = means / (total_images * 255.)
# stds = stds / (total_images * 255.)
# print("Total images: ", total_images)
# print("Means: ", means)
# print("Stds: ", stds)

In [15]:
import torch
import torchvision
from torch.utils.tensorboard import SummaryWriter
from torchvision import datasets, transforms
from torch.optim import AdamW
from torchvision.datasets import CIFAR10
import cv2
import sys
import os
import numpy as np
import random
import skimage
import PIL
import os
import glob
import random
from skimage import data, exposure, img_as_float
import matplotlib.pyplot as plt
import numpy as np
import time
from torchvision.transforms import ToTensor
import argparse
import shutil
import string
from termcolor import colored, cprint
import math as m
from tqdm.notebook import tqdm

def SetupAll(CheckPointPath):
    """
    Inputs: 
    CheckPointPath - Path to save checkpoints/model
    Outputs:
    SaveCheckPoint - Save checkpoint every SaveCheckPoint iteration in every epoch, checkpoint saved automatically after every epoch
    ImageSize - Size of the image
    NumTrainSamples - length(Train)
    TrainLabels - Labels corresponding to Train
    NumClasses - Number of classes
    """
    # Read and Setup Labels
    LabelsPathTrain = 'TxtFiles/LabelsTrain.txt'
    TrainLabels = ReadLabels(LabelsPathTrain)

    # If CheckPointPath doesn't exist make the path
    if(not (os.path.isdir(CheckPointPath))):
        os.makedirs(CheckPointPath)
        
    # Save checkpoint every SaveCheckPoint iteration in every epoch, checkpoint saved automatically after every epoch
    SaveCheckPoint = 100 
    
    # Image Input Shape
    ImageSize = [32, 32, 3]
    NumTrainSamples = len(TrainSet)

    # Number of classes
    NumClasses = 10

    return SaveCheckPoint, ImageSize, NumTrainSamples, TrainLabels, NumClasses


def ReadLabels(LabelsPathTrain):
    if(not (os.path.isfile(LabelsPathTrain))):
        print('ERROR: Train Labels do not exist in '+LabelsPathTrain)
        sys.exit()
    else:
        TrainLabels = open(LabelsPathTrain, 'r')
        TrainLabels = TrainLabels.read()
        TrainLabels = map(float, TrainLabels.split())

    return TrainLabels
    

def ReadDirNames(ReadPath):
    """
    Inputs: 
    ReadPath is the path of the file you want to read
    Outputs:
    DirNames is the data loaded from TxtFiles/DirNames.txt which has full path to all image files without extension
    """
    # Read text files
    DirNames = open(ReadPath, 'r')
    DirNames = DirNames.read()
    DirNames = DirNames.split()
    return DirNames

    
def GenerateBatch(TrainSet, TrainLabels, ImageSize, MiniBatchSize, Indices):
    """
    Inputs: 
    TrainSet - Variable with Subfolder paths to train files
    NOTE that Train can be replaced by Val/Test for generating batch corresponding to validation (held-out testing in this case)/testing
    TrainLabels - Labels corresponding to Train
    NOTE that TrainLabels can be replaced by Val/TestLabels for generating batch corresponding to validation (held-out testing in this case)/testing
    ImageSize is the Size of the Image
    MiniBatchSize is the size of the MiniBatch
   
    Outputs:
    I1Batch - Batch of images
    LabelBatch - Batch of one-hot encoded labels 
    """
    I1Batch = []
    LabelBatch = []
    
    ImageNum = 0
    while ImageNum < MiniBatchSize:
        # Generate random image
        RandIdx = random.randint(0, len(Indices)-1)
        
        ImageNum += 1

        ##########################################################
        # Add any standardization or data augmentation here!
        ##########################################################

        I1, Label = TrainSet[Indices[RandIdx]]

        # Append All Images and Mask
        I1Batch.append(I1)
        LabelBatch.append(torch.tensor(Label))
        
    return torch.stack(I1Batch), torch.stack(LabelBatch)


def PrettyPrint(NumEpochs, DivTrain, MiniBatchSize, NumTrainSamples, LatestFile):
    """
    Prints all stats with all arguments
    """
    print('Number of Epochs Training will run for ' + str(NumEpochs))
    print('Factor of reduction in training data is ' + str(DivTrain))
    print('Mini Batch Size ' + str(MiniBatchSize))
    print('Number of Training Images ' + str(NumTrainSamples))
    if LatestFile is not None:
        print('Loading latest checkpoint with the name ' + LatestFile)              

def TrainOperation(TrainLabels, NumTrainSamples, ImageSize,
                   NumEpochs, MiniBatchSize, SaveCheckPoint, CheckPointPath,
                   DivTrain, LatestFile, TrainSet, LogsPath, TrainIndices, ValIndices):
    """
    Inputs: 
    TrainLabels - Labels corresponding to Train/Test
    NumTrainSamples - length(Train)
    ImageSize - Size of the image
    NumEpochs - Number of passes through the Train data
    MiniBatchSize is the size of the MiniBatch
    SaveCheckPoint - Save checkpoint every SaveCheckPoint iteration in every epoch, checkpoint saved automatically after every epoch
    CheckPointPath - Path to save checkpoints/model
    DivTrain - Divide the data by this number for Epoch calculation, use if you have a lot of dataor for debugging code
    LatestFile - Latest checkpointfile to continue training
    TrainSet - The training dataset
    LogsPath - Path to save Tensorboard Logs
    Outputs:
    Saves Trained network in CheckPointPath and Logs to LogsPath
    """
    # Initialize the model
    model = CIFAR10Model(InputSize=3*32*32,OutputSize=10) 
    ###############################################
    # Fill your optimizer of choice here!
    ###############################################
    Optimizer = torch.optim.Adam(model.parameters(), lr=0.001,weight_decay=0.0005)

    # Tensorboard
    # Create a summary to monitor loss tensor
    Writer = SummaryWriter(LogsPath)

    if LatestFile is not None:
        CheckPoint = torch.load(CheckPointPath + LatestFile + '.ckpt')
        # Extract only numbers from the name
        StartEpoch = int(''.join(c for c in LatestFile.split('a')[0] if c.isdigit()))
        model.load_state_dict(CheckPoint['model_state_dict'])
        print('Loaded latest checkpoint with the name ' + LatestFile + '....')
    else:
        StartEpoch = 0
        print('New model initialized....')
        
    history = []
    for Epochs in tqdm(range(StartEpoch, NumEpochs)):
        TrainLosses = []
        
        NumIterationsPerEpoch = int(NumTrainSamples/MiniBatchSize/DivTrain)
        for PerEpochCounter in tqdm(range(NumIterationsPerEpoch)):
            TrainBatch = GenerateBatch(TrainSet, TrainLabels, ImageSize, MiniBatchSize, TrainIndices)
            
            # Predict output with forward pass
            LossThisBatch = model.training_step(TrainBatch)
            TrainLosses.append(LossThisBatch)
            
            Optimizer.zero_grad()
            LossThisBatch.backward()
            Optimizer.step()
            
            # Save checkpoint every some SaveCheckPoint's iterations
            if PerEpochCounter % SaveCheckPoint == 0:
                # Save the Model learnt in this epoch
                SaveName =  CheckPointPath + str(Epochs) + 'a' + str(PerEpochCounter) + 'model.ckpt'
                
                torch.save({'epoch': Epochs,'model_state_dict': model.state_dict(),'optimizer_state_dict': Optimizer.state_dict(),'loss': LossThisBatch}, SaveName)
                print('\n' + SaveName + ' Model Saved...')

            result = model.validation_step(TrainBatch)
            result['TrainLoss'] = torch.stack(TrainLosses).mean().item()
            model.epoch_end(Epochs*NumIterationsPerEpoch + PerEpochCounter, result)
            history.append(result)
            
            # Tensorboard
            Writer.add_scalar('LossEveryIter', result["loss"], Epochs*NumIterationsPerEpoch + PerEpochCounter)
            Writer.add_scalar('Accuracy', result["acc"], Epochs*NumIterationsPerEpoch + PerEpochCounter)
            # If you don't flush the tensorboard doesn't update until a lot of iterations!
            Writer.flush()

        ValBatch = GenerateBatch(TrainSet, TrainLabels, ImageSize, MiniBatchSize, ValIndices)
        ValResult = model.validation_step(ValBatch)
        Writer.add_scalar('ValidationLossEveryEpoch',ValResult['loss'],Epochs)
        Writer.add_scalar('ValidationAccuracyEveryEpoch',ValResult['acc'],Epochs)
        Writer.flush()
        
        # Save model every epoch
        SaveName = CheckPointPath + str(Epochs) + 'model.ckpt'
        torch.save({'epoch': Epochs,'model_state_dict': model.state_dict(),'optimizer_state_dict': Optimizer.state_dict(),'loss': LossThisBatch}, SaveName)
        print('\n' + SaveName + ' Model Saved...')
        


# Default Hyperparameters
NumEpochs = 20

normalize = torchvision.transforms.Normalize(mean=[0.4914, 0.4822, 0.4465],
                                             std=[0.2470, 0.2435, 0.2616])

# transforms_to_apply = transforms.Compose([transforms.Resize((64,64)),transforms.ToTensor(),normalize])
transformations = transforms.Compose([transforms.ToTensor(), normalize])
TrainSet = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transformations)
ValSet = torchvision.datasets.CIFAR10(root='../../data', train=True,
                                        download=True, transform=transformations)

valid_size = 0.1
num_train = len(TrainSet)
indices = list (range(num_train))
split = int(np.floor(valid_size * num_train))

np.random.seed(42)
np.random.shuffle(indices)

TrainIndices, ValIndices = indices[split:], indices[:split]


DivTrain = 1.0
MiniBatchSize = 1024
LoadCheckPoint = 0
CheckPointPath = "Checkpoints/"
LogsPath = "Logs"

# Setup all needed paraymeters including file reading
SaveCheckPoint, ImageSize, NumTrainSamples, TrainLabels, NumClasses = SetupAll(CheckPointPath)

# Find Latest Checkpoint File
if LoadCheckPoint==1:
    LatestFile = FindLatestModel(CheckPointPath)
else:
    LatestFile = None

# Pretty print stats
PrettyPrint(NumEpochs, DivTrain, MiniBatchSize, NumTrainSamples, LatestFile)

TrainOperation(TrainLabels, NumTrainSamples, ImageSize,
                NumEpochs, MiniBatchSize, SaveCheckPoint, CheckPointPath,
                DivTrain, LatestFile, TrainSet, LogsPath, TrainIndices, ValIndices)

Files already downloaded and verified
Files already downloaded and verified
Number of Epochs Training will run for 20
Factor of reduction in training data is 1.0
Mini Batch Size 1024
Number of Training Images 50000
New model initialized....


  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/0a0model.ckpt Model Saved...
Epoch [0], loss: 2.2600, acc: 0.1729
Epoch [1], loss: 2.1968, acc: 0.2002
Epoch [2], loss: 2.1570, acc: 0.1973
Epoch [3], loss: 2.0991, acc: 0.2607
Epoch [4], loss: 2.0485, acc: 0.2490
Epoch [5], loss: 1.9643, acc: 0.3037
Epoch [6], loss: 1.9474, acc: 0.3057
Epoch [7], loss: 1.9341, acc: 0.3066
Epoch [8], loss: 1.8889, acc: 0.3008
Epoch [9], loss: 1.8796, acc: 0.3301
Epoch [10], loss: 1.8339, acc: 0.3623
Epoch [11], loss: 1.7888, acc: 0.3730
Epoch [12], loss: 1.8112, acc: 0.3252
Epoch [13], loss: 1.7889, acc: 0.3730
Epoch [14], loss: 1.7660, acc: 0.3691
Epoch [15], loss: 1.8019, acc: 0.3740
Epoch [16], loss: 1.7699, acc: 0.3770
Epoch [17], loss: 1.7478, acc: 0.3564
Epoch [18], loss: 1.7133, acc: 0.4004
Epoch [19], loss: 1.7011, acc: 0.3994
Epoch [20], loss: 1.7475, acc: 0.3867
Epoch [21], loss: 1.7240, acc: 0.3838
Epoch [22], loss: 1.6905, acc: 0.3955
Epoch [23], loss: 1.7303, acc: 0.3867
Epoch [24], loss: 1.6520, acc: 0.4082
Epoch [25], loss: 

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/1a0model.ckpt Model Saved...
Epoch [48], loss: 1.5649, acc: 0.4463
Epoch [49], loss: 1.6081, acc: 0.4180
Epoch [50], loss: 1.5606, acc: 0.4336
Epoch [51], loss: 1.5544, acc: 0.4551
Epoch [52], loss: 1.5881, acc: 0.4346
Epoch [53], loss: 1.5326, acc: 0.4521
Epoch [54], loss: 1.5505, acc: 0.4404
Epoch [55], loss: 1.5776, acc: 0.4395
Epoch [56], loss: 1.5048, acc: 0.4707
Epoch [57], loss: 1.5612, acc: 0.4297
Epoch [58], loss: 1.5265, acc: 0.4824
Epoch [59], loss: 1.4993, acc: 0.4639
Epoch [60], loss: 1.5192, acc: 0.4727
Epoch [61], loss: 1.4917, acc: 0.4834
Epoch [62], loss: 1.4967, acc: 0.4746
Epoch [63], loss: 1.5114, acc: 0.4727
Epoch [64], loss: 1.5325, acc: 0.4629
Epoch [65], loss: 1.5198, acc: 0.4551
Epoch [66], loss: 1.5486, acc: 0.4658
Epoch [67], loss: 1.4723, acc: 0.4707
Epoch [68], loss: 1.4450, acc: 0.4756
Epoch [69], loss: 1.4946, acc: 0.4756
Epoch [70], loss: 1.4602, acc: 0.4844
Epoch [71], loss: 1.4814, acc: 0.4678
Epoch [72], loss: 1.4799, acc: 0.4814
Epoch [7

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/2a0model.ckpt Model Saved...
Epoch [96], loss: 1.4249, acc: 0.4863
Epoch [97], loss: 1.4038, acc: 0.5020
Epoch [98], loss: 1.3325, acc: 0.5283
Epoch [99], loss: 1.3808, acc: 0.5156
Epoch [100], loss: 1.3905, acc: 0.5000
Epoch [101], loss: 1.4379, acc: 0.4990
Epoch [102], loss: 1.3126, acc: 0.5459
Epoch [103], loss: 1.3657, acc: 0.5264
Epoch [104], loss: 1.3905, acc: 0.5078
Epoch [105], loss: 1.4148, acc: 0.4941
Epoch [106], loss: 1.3458, acc: 0.5352
Epoch [107], loss: 1.2955, acc: 0.5566
Epoch [108], loss: 1.3511, acc: 0.5068
Epoch [109], loss: 1.3869, acc: 0.5205
Epoch [110], loss: 1.3829, acc: 0.5107
Epoch [111], loss: 1.4207, acc: 0.5146
Epoch [112], loss: 1.3687, acc: 0.5107
Epoch [113], loss: 1.3471, acc: 0.5215
Epoch [114], loss: 1.3362, acc: 0.5488
Epoch [115], loss: 1.2964, acc: 0.5479
Epoch [116], loss: 1.3275, acc: 0.5488
Epoch [117], loss: 1.3296, acc: 0.5527
Epoch [118], loss: 1.4049, acc: 0.5244
Epoch [119], loss: 1.3880, acc: 0.5088
Epoch [120], loss: 1.3939,

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/3a0model.ckpt Model Saved...
Epoch [144], loss: 1.3559, acc: 0.5303
Epoch [145], loss: 1.2317, acc: 0.5674
Epoch [146], loss: 1.2716, acc: 0.5850
Epoch [147], loss: 1.2625, acc: 0.5645
Epoch [148], loss: 1.2728, acc: 0.5693
Epoch [149], loss: 1.2431, acc: 0.5693
Epoch [150], loss: 1.2800, acc: 0.5498
Epoch [151], loss: 1.2936, acc: 0.5420
Epoch [152], loss: 1.2742, acc: 0.5488
Epoch [153], loss: 1.2541, acc: 0.5615
Epoch [154], loss: 1.2805, acc: 0.5635
Epoch [155], loss: 1.2375, acc: 0.5596
Epoch [156], loss: 1.2444, acc: 0.5645
Epoch [157], loss: 1.2395, acc: 0.5635
Epoch [158], loss: 1.2441, acc: 0.5654
Epoch [159], loss: 1.2144, acc: 0.5762
Epoch [160], loss: 1.2027, acc: 0.5752
Epoch [161], loss: 1.2132, acc: 0.5752
Epoch [162], loss: 1.3274, acc: 0.5410
Epoch [163], loss: 1.2303, acc: 0.5664
Epoch [164], loss: 1.2711, acc: 0.5557
Epoch [165], loss: 1.2061, acc: 0.5840
Epoch [166], loss: 1.2323, acc: 0.5703
Epoch [167], loss: 1.2533, acc: 0.5586
Epoch [168], loss: 1.2

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/4a0model.ckpt Model Saved...
Epoch [192], loss: 1.2001, acc: 0.5586
Epoch [193], loss: 1.1943, acc: 0.5869
Epoch [194], loss: 1.2673, acc: 0.5654
Epoch [195], loss: 1.2783, acc: 0.5352
Epoch [196], loss: 1.2388, acc: 0.5684
Epoch [197], loss: 1.1295, acc: 0.6094
Epoch [198], loss: 1.2086, acc: 0.5625
Epoch [199], loss: 1.1945, acc: 0.5850
Epoch [200], loss: 1.2185, acc: 0.5889
Epoch [201], loss: 1.2396, acc: 0.5732
Epoch [202], loss: 1.1343, acc: 0.6074
Epoch [203], loss: 1.2210, acc: 0.5850
Epoch [204], loss: 1.2072, acc: 0.5762
Epoch [205], loss: 1.1627, acc: 0.5898
Epoch [206], loss: 1.1401, acc: 0.5938
Epoch [207], loss: 1.1767, acc: 0.5918
Epoch [208], loss: 1.1432, acc: 0.5908
Epoch [209], loss: 1.1968, acc: 0.5869
Epoch [210], loss: 1.1614, acc: 0.5977
Epoch [211], loss: 1.1717, acc: 0.5752
Epoch [212], loss: 1.1828, acc: 0.5762
Epoch [213], loss: 1.1617, acc: 0.5820
Epoch [214], loss: 1.1488, acc: 0.6113
Epoch [215], loss: 1.1852, acc: 0.5850
Epoch [216], loss: 1.2

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/5a0model.ckpt Model Saved...
Epoch [240], loss: 1.1386, acc: 0.5938
Epoch [241], loss: 1.1393, acc: 0.6201
Epoch [242], loss: 1.1156, acc: 0.6299
Epoch [243], loss: 1.1060, acc: 0.6357
Epoch [244], loss: 1.1523, acc: 0.5898
Epoch [245], loss: 1.1312, acc: 0.6035
Epoch [246], loss: 1.1171, acc: 0.6074
Epoch [247], loss: 1.1201, acc: 0.6094
Epoch [248], loss: 1.1490, acc: 0.6240
Epoch [249], loss: 1.0678, acc: 0.6367
Epoch [250], loss: 1.1166, acc: 0.6055
Epoch [251], loss: 1.1764, acc: 0.5947
Epoch [252], loss: 1.1326, acc: 0.6133
Epoch [253], loss: 1.1498, acc: 0.6162
Epoch [254], loss: 1.0772, acc: 0.6230
Epoch [255], loss: 1.1640, acc: 0.5947
Epoch [256], loss: 1.1302, acc: 0.6152
Epoch [257], loss: 1.1610, acc: 0.6055
Epoch [258], loss: 1.0797, acc: 0.6084
Epoch [259], loss: 1.0959, acc: 0.6133
Epoch [260], loss: 1.0666, acc: 0.6338
Epoch [261], loss: 1.0490, acc: 0.6475
Epoch [262], loss: 1.1431, acc: 0.6025
Epoch [263], loss: 1.0832, acc: 0.6279
Epoch [264], loss: 1.1

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/6a0model.ckpt Model Saved...
Epoch [288], loss: 1.0839, acc: 0.6191
Epoch [289], loss: 0.9567, acc: 0.6514
Epoch [290], loss: 1.0838, acc: 0.6211
Epoch [291], loss: 0.9988, acc: 0.6807
Epoch [292], loss: 1.0288, acc: 0.6367
Epoch [293], loss: 1.0897, acc: 0.6299
Epoch [294], loss: 1.0793, acc: 0.6240
Epoch [295], loss: 1.1116, acc: 0.6250
Epoch [296], loss: 1.0543, acc: 0.6367
Epoch [297], loss: 0.9991, acc: 0.6523
Epoch [298], loss: 1.0705, acc: 0.6367
Epoch [299], loss: 1.0658, acc: 0.6084
Epoch [300], loss: 1.0190, acc: 0.6465
Epoch [301], loss: 1.0472, acc: 0.6338
Epoch [302], loss: 1.0148, acc: 0.6621
Epoch [303], loss: 1.0305, acc: 0.6406
Epoch [304], loss: 1.0406, acc: 0.6318
Epoch [305], loss: 0.9697, acc: 0.6660
Epoch [306], loss: 1.0435, acc: 0.6299
Epoch [307], loss: 0.9842, acc: 0.6758
Epoch [308], loss: 0.9998, acc: 0.6572
Epoch [309], loss: 1.0113, acc: 0.6504
Epoch [310], loss: 0.9632, acc: 0.6885
Epoch [311], loss: 1.0351, acc: 0.6338
Epoch [312], loss: 1.0

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/7a0model.ckpt Model Saved...
Epoch [336], loss: 1.0116, acc: 0.6592
Epoch [337], loss: 0.9678, acc: 0.6963
Epoch [338], loss: 0.9617, acc: 0.6748
Epoch [339], loss: 0.9763, acc: 0.6699
Epoch [340], loss: 0.9657, acc: 0.6729
Epoch [341], loss: 0.9846, acc: 0.6611
Epoch [342], loss: 0.9744, acc: 0.6582
Epoch [343], loss: 0.9637, acc: 0.6680
Epoch [344], loss: 0.9269, acc: 0.6846
Epoch [345], loss: 0.9655, acc: 0.6729
Epoch [346], loss: 0.9765, acc: 0.6621
Epoch [347], loss: 0.9809, acc: 0.6592
Epoch [348], loss: 0.9524, acc: 0.6562
Epoch [349], loss: 0.9891, acc: 0.6572
Epoch [350], loss: 1.0098, acc: 0.6562
Epoch [351], loss: 1.0196, acc: 0.6445
Epoch [352], loss: 0.9896, acc: 0.6504
Epoch [353], loss: 0.9184, acc: 0.6846
Epoch [354], loss: 0.9952, acc: 0.6523
Epoch [355], loss: 0.9844, acc: 0.6621
Epoch [356], loss: 0.9980, acc: 0.6553
Epoch [357], loss: 0.9703, acc: 0.6797
Epoch [358], loss: 0.9963, acc: 0.6475
Epoch [359], loss: 1.0189, acc: 0.6494
Epoch [360], loss: 1.0

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/8a0model.ckpt Model Saved...
Epoch [384], loss: 0.9530, acc: 0.6582
Epoch [385], loss: 0.9145, acc: 0.6855
Epoch [386], loss: 0.9214, acc: 0.6934
Epoch [387], loss: 0.9309, acc: 0.6826
Epoch [388], loss: 0.9180, acc: 0.6797
Epoch [389], loss: 0.9119, acc: 0.6992
Epoch [390], loss: 0.8859, acc: 0.6992
Epoch [391], loss: 0.9311, acc: 0.6895
Epoch [392], loss: 0.9132, acc: 0.6807
Epoch [393], loss: 0.9105, acc: 0.6846
Epoch [394], loss: 0.9454, acc: 0.6699
Epoch [395], loss: 0.9219, acc: 0.6875
Epoch [396], loss: 0.9074, acc: 0.6895
Epoch [397], loss: 0.9105, acc: 0.6953
Epoch [398], loss: 0.9254, acc: 0.6934
Epoch [399], loss: 0.9168, acc: 0.6992
Epoch [400], loss: 0.8915, acc: 0.6895
Epoch [401], loss: 0.8895, acc: 0.6992
Epoch [402], loss: 0.8698, acc: 0.6992
Epoch [403], loss: 0.9437, acc: 0.6758
Epoch [404], loss: 0.8935, acc: 0.7002
Epoch [405], loss: 0.8615, acc: 0.6953
Epoch [406], loss: 0.9152, acc: 0.6807
Epoch [407], loss: 0.9032, acc: 0.6660
Epoch [408], loss: 0.8

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/9a0model.ckpt Model Saved...
Epoch [432], loss: 0.8610, acc: 0.7158
Epoch [433], loss: 0.8657, acc: 0.6973
Epoch [434], loss: 0.8392, acc: 0.7266
Epoch [435], loss: 0.8863, acc: 0.7070
Epoch [436], loss: 0.8597, acc: 0.7188
Epoch [437], loss: 0.9015, acc: 0.6992
Epoch [438], loss: 0.8110, acc: 0.7402
Epoch [439], loss: 0.9321, acc: 0.6826
Epoch [440], loss: 0.8288, acc: 0.7148
Epoch [441], loss: 0.9111, acc: 0.6846
Epoch [442], loss: 0.8626, acc: 0.7061
Epoch [443], loss: 0.8368, acc: 0.7266
Epoch [444], loss: 0.8997, acc: 0.6807
Epoch [445], loss: 0.8324, acc: 0.7256
Epoch [446], loss: 0.8480, acc: 0.7109
Epoch [447], loss: 0.8886, acc: 0.6953
Epoch [448], loss: 0.8781, acc: 0.6836
Epoch [449], loss: 0.8780, acc: 0.7139
Epoch [450], loss: 0.8554, acc: 0.7227
Epoch [451], loss: 0.8743, acc: 0.7021
Epoch [452], loss: 0.9318, acc: 0.6807
Epoch [453], loss: 0.8322, acc: 0.7100
Epoch [454], loss: 0.8645, acc: 0.7070
Epoch [455], loss: 0.8655, acc: 0.7129
Epoch [456], loss: 0.7

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/10a0model.ckpt Model Saved...
Epoch [480], loss: 0.8107, acc: 0.7070
Epoch [481], loss: 0.8202, acc: 0.7139
Epoch [482], loss: 0.7448, acc: 0.7520
Epoch [483], loss: 0.8010, acc: 0.7344
Epoch [484], loss: 0.7963, acc: 0.7305
Epoch [485], loss: 0.7711, acc: 0.7324
Epoch [486], loss: 0.8250, acc: 0.7168
Epoch [487], loss: 0.8089, acc: 0.7207
Epoch [488], loss: 0.7920, acc: 0.7129
Epoch [489], loss: 0.7914, acc: 0.7334
Epoch [490], loss: 0.7754, acc: 0.7451
Epoch [491], loss: 0.7494, acc: 0.7471
Epoch [492], loss: 0.7353, acc: 0.7480
Epoch [493], loss: 0.7882, acc: 0.7314
Epoch [494], loss: 0.8267, acc: 0.7119
Epoch [495], loss: 0.8053, acc: 0.7393
Epoch [496], loss: 0.7211, acc: 0.7656
Epoch [497], loss: 0.7764, acc: 0.7236
Epoch [498], loss: 0.7244, acc: 0.7363
Epoch [499], loss: 0.7557, acc: 0.7461
Epoch [500], loss: 0.7873, acc: 0.7168
Epoch [501], loss: 0.7722, acc: 0.7539
Epoch [502], loss: 0.7811, acc: 0.7451
Epoch [503], loss: 0.7595, acc: 0.7432
Epoch [504], loss: 0.

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/11a0model.ckpt Model Saved...
Epoch [528], loss: 0.7465, acc: 0.7461
Epoch [529], loss: 0.7131, acc: 0.7686
Epoch [530], loss: 0.7549, acc: 0.7480
Epoch [531], loss: 0.7069, acc: 0.7451
Epoch [532], loss: 0.7813, acc: 0.7344
Epoch [533], loss: 0.7360, acc: 0.7529
Epoch [534], loss: 0.7393, acc: 0.7529
Epoch [535], loss: 0.7036, acc: 0.7666
Epoch [536], loss: 0.7723, acc: 0.7520
Epoch [537], loss: 0.7557, acc: 0.7334
Epoch [538], loss: 0.7282, acc: 0.7480
Epoch [539], loss: 0.7289, acc: 0.7578
Epoch [540], loss: 0.7366, acc: 0.7529
Epoch [541], loss: 0.7705, acc: 0.7246
Epoch [542], loss: 0.7580, acc: 0.7314
Epoch [543], loss: 0.7910, acc: 0.7285
Epoch [544], loss: 0.7753, acc: 0.7510
Epoch [545], loss: 0.7705, acc: 0.7393
Epoch [546], loss: 0.7445, acc: 0.7510
Epoch [547], loss: 0.7664, acc: 0.7461
Epoch [548], loss: 0.7635, acc: 0.7324
Epoch [549], loss: 0.7688, acc: 0.7334
Epoch [550], loss: 0.6943, acc: 0.7637
Epoch [551], loss: 0.7426, acc: 0.7500
Epoch [552], loss: 0.

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/12a0model.ckpt Model Saved...
Epoch [576], loss: 0.6769, acc: 0.7588
Epoch [577], loss: 0.7349, acc: 0.7393
Epoch [578], loss: 0.7411, acc: 0.7393
Epoch [579], loss: 0.6985, acc: 0.7646
Epoch [580], loss: 0.7340, acc: 0.7334
Epoch [581], loss: 0.7383, acc: 0.7461
Epoch [582], loss: 0.6796, acc: 0.7617
Epoch [583], loss: 0.6251, acc: 0.7842
Epoch [584], loss: 0.6321, acc: 0.7861
Epoch [585], loss: 0.6763, acc: 0.7529
Epoch [586], loss: 0.7466, acc: 0.7441
Epoch [587], loss: 0.7014, acc: 0.7598
Epoch [588], loss: 0.6795, acc: 0.7607
Epoch [589], loss: 0.7013, acc: 0.7695
Epoch [590], loss: 0.7067, acc: 0.7539
Epoch [591], loss: 0.6411, acc: 0.7812
Epoch [592], loss: 0.6894, acc: 0.7695
Epoch [593], loss: 0.6894, acc: 0.7617
Epoch [594], loss: 0.6896, acc: 0.7734
Epoch [595], loss: 0.6784, acc: 0.7793
Epoch [596], loss: 0.6609, acc: 0.7881
Epoch [597], loss: 0.6853, acc: 0.7627
Epoch [598], loss: 0.6635, acc: 0.7773
Epoch [599], loss: 0.6379, acc: 0.7910
Epoch [600], loss: 0.

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/13a0model.ckpt Model Saved...
Epoch [624], loss: 0.6537, acc: 0.7725
Epoch [625], loss: 0.6510, acc: 0.7812
Epoch [626], loss: 0.6103, acc: 0.7979
Epoch [627], loss: 0.6478, acc: 0.7861
Epoch [628], loss: 0.6402, acc: 0.8027
Epoch [629], loss: 0.6209, acc: 0.7871
Epoch [630], loss: 0.6392, acc: 0.7881
Epoch [631], loss: 0.6628, acc: 0.7783
Epoch [632], loss: 0.6531, acc: 0.7812
Epoch [633], loss: 0.6652, acc: 0.7686
Epoch [634], loss: 0.6291, acc: 0.7920
Epoch [635], loss: 0.5779, acc: 0.8125
Epoch [636], loss: 0.6503, acc: 0.7832
Epoch [637], loss: 0.6788, acc: 0.7656
Epoch [638], loss: 0.6433, acc: 0.7803
Epoch [639], loss: 0.6550, acc: 0.7598
Epoch [640], loss: 0.6401, acc: 0.7803
Epoch [641], loss: 0.6595, acc: 0.7900
Epoch [642], loss: 0.6670, acc: 0.7793
Epoch [643], loss: 0.6926, acc: 0.7695
Epoch [644], loss: 0.6440, acc: 0.7783
Epoch [645], loss: 0.6529, acc: 0.7783
Epoch [646], loss: 0.6472, acc: 0.7832
Epoch [647], loss: 0.6049, acc: 0.8086
Epoch [648], loss: 0.

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/14a0model.ckpt Model Saved...
Epoch [672], loss: 0.6622, acc: 0.7715
Epoch [673], loss: 0.6499, acc: 0.7852
Epoch [674], loss: 0.6614, acc: 0.7783
Epoch [675], loss: 0.6697, acc: 0.7627
Epoch [676], loss: 0.6376, acc: 0.7812
Epoch [677], loss: 0.6149, acc: 0.8076
Epoch [678], loss: 0.6252, acc: 0.7793
Epoch [679], loss: 0.6724, acc: 0.7871
Epoch [680], loss: 0.6407, acc: 0.7900
Epoch [681], loss: 0.6454, acc: 0.7676
Epoch [682], loss: 0.5974, acc: 0.8154
Epoch [683], loss: 0.6582, acc: 0.7705
Epoch [684], loss: 0.6053, acc: 0.7852
Epoch [685], loss: 0.6517, acc: 0.7832
Epoch [686], loss: 0.6782, acc: 0.7705
Epoch [687], loss: 0.5939, acc: 0.8164
Epoch [688], loss: 0.6165, acc: 0.7871
Epoch [689], loss: 0.6348, acc: 0.7822
Epoch [690], loss: 0.5554, acc: 0.8037
Epoch [691], loss: 0.6272, acc: 0.7842
Epoch [692], loss: 0.6040, acc: 0.8076
Epoch [693], loss: 0.5829, acc: 0.8086
Epoch [694], loss: 0.5705, acc: 0.7988
Epoch [695], loss: 0.5775, acc: 0.8213
Epoch [696], loss: 0.

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/15a0model.ckpt Model Saved...
Epoch [720], loss: 0.6013, acc: 0.8027
Epoch [721], loss: 0.5576, acc: 0.8047
Epoch [722], loss: 0.5882, acc: 0.7871
Epoch [723], loss: 0.5392, acc: 0.8135
Epoch [724], loss: 0.6047, acc: 0.8037
Epoch [725], loss: 0.5953, acc: 0.7939
Epoch [726], loss: 0.5752, acc: 0.8086
Epoch [727], loss: 0.5421, acc: 0.8291
Epoch [728], loss: 0.5272, acc: 0.8330
Epoch [729], loss: 0.5130, acc: 0.8271
Epoch [730], loss: 0.6008, acc: 0.8086
Epoch [731], loss: 0.5865, acc: 0.8115
Epoch [732], loss: 0.5351, acc: 0.8213
Epoch [733], loss: 0.5166, acc: 0.8340
Epoch [734], loss: 0.5447, acc: 0.8281
Epoch [735], loss: 0.4866, acc: 0.8369
Epoch [736], loss: 0.5574, acc: 0.8203
Epoch [737], loss: 0.5372, acc: 0.8184
Epoch [738], loss: 0.5514, acc: 0.8135
Epoch [739], loss: 0.5089, acc: 0.8311
Epoch [740], loss: 0.5320, acc: 0.8320
Epoch [741], loss: 0.5173, acc: 0.8486
Epoch [742], loss: 0.5430, acc: 0.8135
Epoch [743], loss: 0.4966, acc: 0.8516
Epoch [744], loss: 0.

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/16a0model.ckpt Model Saved...
Epoch [768], loss: 0.5073, acc: 0.8320
Epoch [769], loss: 0.5513, acc: 0.8076
Epoch [770], loss: 0.5151, acc: 0.8389
Epoch [771], loss: 0.4797, acc: 0.8457
Epoch [772], loss: 0.5261, acc: 0.8164
Epoch [773], loss: 0.5036, acc: 0.8311
Epoch [774], loss: 0.4915, acc: 0.8301
Epoch [775], loss: 0.4788, acc: 0.8252
Epoch [776], loss: 0.5045, acc: 0.8223
Epoch [777], loss: 0.5144, acc: 0.8291
Epoch [778], loss: 0.4963, acc: 0.8330
Epoch [779], loss: 0.4604, acc: 0.8457
Epoch [780], loss: 0.4687, acc: 0.8418
Epoch [781], loss: 0.5947, acc: 0.8037
Epoch [782], loss: 0.5337, acc: 0.8223
Epoch [783], loss: 0.5132, acc: 0.8145
Epoch [784], loss: 0.4973, acc: 0.8447
Epoch [785], loss: 0.5097, acc: 0.8320
Epoch [786], loss: 0.4617, acc: 0.8496
Epoch [787], loss: 0.4609, acc: 0.8506
Epoch [788], loss: 0.4778, acc: 0.8408
Epoch [789], loss: 0.4723, acc: 0.8486
Epoch [790], loss: 0.4983, acc: 0.8477
Epoch [791], loss: 0.4983, acc: 0.8369
Epoch [792], loss: 0.

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/17a0model.ckpt Model Saved...
Epoch [816], loss: 0.4759, acc: 0.8418
Epoch [817], loss: 0.4486, acc: 0.8584
Epoch [818], loss: 0.5138, acc: 0.8281
Epoch [819], loss: 0.4650, acc: 0.8486
Epoch [820], loss: 0.5045, acc: 0.8203
Epoch [821], loss: 0.5015, acc: 0.8242
Epoch [822], loss: 0.5561, acc: 0.8096
Epoch [823], loss: 0.5094, acc: 0.8135
Epoch [824], loss: 0.4958, acc: 0.8369
Epoch [825], loss: 0.4971, acc: 0.8369
Epoch [826], loss: 0.4751, acc: 0.8535
Epoch [827], loss: 0.5272, acc: 0.8252
Epoch [828], loss: 0.5047, acc: 0.8262
Epoch [829], loss: 0.5295, acc: 0.8096
Epoch [830], loss: 0.4830, acc: 0.8359
Epoch [831], loss: 0.4808, acc: 0.8379
Epoch [832], loss: 0.4906, acc: 0.8408
Epoch [833], loss: 0.4931, acc: 0.8350
Epoch [834], loss: 0.5033, acc: 0.8213
Epoch [835], loss: 0.4822, acc: 0.8447
Epoch [836], loss: 0.4914, acc: 0.8398
Epoch [837], loss: 0.5426, acc: 0.8174
Epoch [838], loss: 0.5204, acc: 0.8320
Epoch [839], loss: 0.4878, acc: 0.8271
Epoch [840], loss: 0.

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/18a0model.ckpt Model Saved...
Epoch [864], loss: 0.4232, acc: 0.8613
Epoch [865], loss: 0.4456, acc: 0.8555
Epoch [866], loss: 0.4406, acc: 0.8506
Epoch [867], loss: 0.4869, acc: 0.8408
Epoch [868], loss: 0.4531, acc: 0.8457
Epoch [869], loss: 0.4653, acc: 0.8408
Epoch [870], loss: 0.4408, acc: 0.8486
Epoch [871], loss: 0.4256, acc: 0.8613
Epoch [872], loss: 0.4486, acc: 0.8613
Epoch [873], loss: 0.4440, acc: 0.8574
Epoch [874], loss: 0.4339, acc: 0.8643
Epoch [875], loss: 0.4430, acc: 0.8604
Epoch [876], loss: 0.4226, acc: 0.8525
Epoch [877], loss: 0.3956, acc: 0.8779
Epoch [878], loss: 0.3689, acc: 0.8867
Epoch [879], loss: 0.4469, acc: 0.8506
Epoch [880], loss: 0.4201, acc: 0.8633
Epoch [881], loss: 0.4242, acc: 0.8613
Epoch [882], loss: 0.4156, acc: 0.8555
Epoch [883], loss: 0.4555, acc: 0.8457
Epoch [884], loss: 0.4540, acc: 0.8584
Epoch [885], loss: 0.3883, acc: 0.8809
Epoch [886], loss: 0.4472, acc: 0.8506
Epoch [887], loss: 0.4525, acc: 0.8477
Epoch [888], loss: 0.

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/19a0model.ckpt Model Saved...
Epoch [912], loss: 0.4624, acc: 0.8516
Epoch [913], loss: 0.3579, acc: 0.8945
Epoch [914], loss: 0.4571, acc: 0.8477
Epoch [915], loss: 0.4673, acc: 0.8340
Epoch [916], loss: 0.4170, acc: 0.8467
Epoch [917], loss: 0.4312, acc: 0.8604
Epoch [918], loss: 0.4114, acc: 0.8711
Epoch [919], loss: 0.4043, acc: 0.8682
Epoch [920], loss: 0.4316, acc: 0.8496
Epoch [921], loss: 0.4178, acc: 0.8730
Epoch [922], loss: 0.4473, acc: 0.8506
Epoch [923], loss: 0.4515, acc: 0.8457
Epoch [924], loss: 0.4072, acc: 0.8662
Epoch [925], loss: 0.4212, acc: 0.8701
Epoch [926], loss: 0.4120, acc: 0.8721
Epoch [927], loss: 0.4088, acc: 0.8623
Epoch [928], loss: 0.4255, acc: 0.8525
Epoch [929], loss: 0.4081, acc: 0.8682
Epoch [930], loss: 0.4086, acc: 0.8740
Epoch [931], loss: 0.4111, acc: 0.8691
Epoch [932], loss: 0.4320, acc: 0.8574
Epoch [933], loss: 0.4281, acc: 0.8633
Epoch [934], loss: 0.4285, acc: 0.8584
Epoch [935], loss: 0.4138, acc: 0.8711
Epoch [936], loss: 0.

### Test your neural network

In [17]:
import cv2
import os
import sys
import glob
import random
from skimage import data, exposure, img_as_float
import matplotlib.pyplot as plt
import numpy as np
import time
from torchvision.transforms import ToTensor
import argparse
import shutil
import string
import math as m
from sklearn.metrics import confusion_matrix
from tqdm.notebook import tqdm
import torch

def SetupAll():
    """
    Outputs:
    ImageSize - Size of the Image
    """   
    # Image Input Shape
    ImageSize = [32, 32, 3]

    return ImageSize

def StandardizeInputs(Img):
    ##########################################################################
    # Add any standardization or cropping/resizing if used in Training here!
    ##########################################################################
    return Img
    
def ReadImages(Img):
    """
    Outputs:
    I1Combined - I1 image after any standardization and/or cropping/resizing to ImageSize
    I1 - Original I1 image for visualization purposes only
    """    
    I1 = Img
    
    if(I1 is None):
        # OpenCV returns empty list if image is not read! 
        print('ERROR: Image I1 cannot be read')
        sys.exit()
        
    I1S = StandardizeInputs(np.float32(I1))

    I1Combined = np.expand_dims(I1S, axis=0)

    return I1Combined, I1
                

def TestOperation(ImageSize, ModelPath, TestSet, LabelsPathPred):
    """
    Inputs: 
    ImageSize is the size of the image
    ModelPath - Path to load trained model from
    TestSet - The test dataset
    LabelsPathPred - Path to save predictions
    Outputs:
    Predictions written to TxtFiles/PredOut.txt
    """
    # Predict output with forward pass, MiniBatchSize for Test is 1
    model = CIFAR10Model(InputSize=3*32*32,OutputSize=10) 
    
    CheckPoint = torch.load(ModelPath)
    model.load_state_dict(CheckPoint['model_state_dict'])
    print('Number of parameters in this model are %d ' % len(model.state_dict().items()))
    
    OutSaveT = open(LabelsPathPred, 'w')

    for count in tqdm(range(len(TestSet))): 
        Img, Label = TestSet[count]
        Img, ImgOrg = ReadImages(Img)
        PredT = torch.argmax(model(torch.tensor(Img))).item()

        OutSaveT.write(str(PredT)+'\n')
    OutSaveT.close()

def Accuracy(Pred, GT):
    """
    Inputs: 
    Pred are the predicted labels
    GT are the ground truth labels
    Outputs:
    Accuracy in percentage
    """
    return (np.sum(np.array(Pred)==np.array(GT))*100.0/len(Pred))

def ReadLabels(LabelsPathTest, LabelsPathPred):
    if(not (os.path.isfile(LabelsPathTest))):
        print('ERROR: Test Labels do not exist in '+LabelsPathTest)
        sys.exit()
    else:
        LabelTest = open(LabelsPathTest, 'r')
        LabelTest = LabelTest.read()
        LabelTest = map(float, LabelTest.split())

    if(not (os.path.isfile(LabelsPathPred))):
        print('ERROR: Pred Labels do not exist in '+LabelsPathPred)
        sys.exit()
    else:
        LabelPred = open(LabelsPathPred, 'r')
        LabelPred = LabelPred.read()
        LabelPred = map(float, LabelPred.split())
        
    return LabelTest, LabelPred

def ConfusionMatrix(LabelsTrue, LabelsPred):
    """
    LabelsTrue - True labels
    LabelsPred - Predicted labels
    """

    # Get the confusion matrix using sklearn.
    LabelsTrue, LabelsPred = list(LabelsTrue), list(LabelsPred)
    cm = confusion_matrix(y_true=LabelsTrue,  # True class for test-set.
                          y_pred=LabelsPred)  # Predicted class.

    # Print the confusion matrix as text.
    for i in range(10):
        print(str(cm[i, :]) + ' ({0})'.format(i))

    # Print the class-numbers for easy reference.
    class_numbers = [" ({0})".format(i) for i in range(10)]
    print("".join(class_numbers))

    print('Accuracy: '+ str(Accuracy(LabelsPred, LabelsTrue)), '%')


ModelPath = "Checkpoints/19model.ckpt"
LabelsPath = "TxtFiles/LabelsTest.txt"

TestSet = CIFAR10(root='data/', train=False, transform=transformations)

# Setup all needed parameters including file reading
ImageSize = SetupAll()

# Define PlaceHolder variables for Input and Predicted output
LabelsPathPred = 'TxtFiles/PredOut.txt' # Path to save predicted labels

TestOperation(ImageSize, ModelPath, TestSet, LabelsPathPred)

# Plot Confusion Matrix
LabelsTrue, LabelsPred = ReadLabels(LabelsPath, LabelsPathPred)
ConfusionMatrix(LabelsTrue, LabelsPred) 

Number of parameters in this model are 10 


  0%|          | 0/10000 [00:00<?, ?it/s]

[624  38  49  17  42  15  15  27  97  76] (0)
[ 44 648  18  24  10   7  14  19  61 155] (1)
[ 76  16 435  74 133  89  63  75  15  24] (2)
[ 23  19  80 336  65 232  91  89  27  38] (3)
[ 46  16 122  60 473  55  79 101  28  20] (4)
[ 16  14  78 161  71 488  44  86  17  25] (5)
[ 13  16  78  90  94  68 577  21  12  31] (6)
[ 31   6  29  53  71  97  14 655   9  35] (7)
[106  70  17  21  20  18  12  12 660  64] (8)
[ 49 159  15  36  16  22  17  46  34 606] (9)
 (0) (1) (2) (3) (4) (5) (6) (7) (8) (9)
Accuracy: 55.02 %
