# RBE/CS549 Fall 2022: Computer Vision
## Homework 0: Alohomora

Author(s): 
Prof. Nitin J. Sanket (nsanket@wpi.edu), Lening Li (lli4@wpi.edu), Gejji, Vaishnavi Vivek (vgejji@wpi.edu)

Robotics Engineering Department,

Worcester Polytechnic Institute

Code adapted from CMSC733 at the University of Maryland, College Park.

## Phase 2

### Neural Network Construction

In [1]:
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

def accuracy(outputs, labels):
    _, preds = torch.max(outputs, dim=1)
    return torch.tensor(torch.sum(preds == labels).item() / len(preds))

def loss_fn(out, labels):
    ###############################################
    # Fill your loss function of choice here!
    ###############################################
    loss = nn.CrossEntropyLoss()
    loss = loss(out, labels)
    return loss

class ImageClassificationBase(nn.Module):
    def training_step(self, batch):
        images, labels = batch 
        out = self(images)                  # Generate predictions
        loss = loss_fn(out, labels) # Calculate loss
        return loss
    
    def validation_step(self, batch):
        images, labels = batch 
        out = self(images)                    # Generate predictions
        loss = loss_fn(out, labels)   # Calculate loss
        acc = accuracy(out, labels)           # Calculate accuracy
        return {'loss': loss.detach(), 'acc': acc}
        
    def validation_epoch_end(self, outputs):
        batch_losses = [x['loss'] for x in outputs]
        epoch_loss = torch.stack(batch_losses).mean()   # Combine losses
        batch_accs = [x['acc'] for x in outputs]
        epoch_acc = torch.stack(batch_accs).mean()      # Combine accuracies
        return {'loss': epoch_loss.item(), 'acc': epoch_acc.item()}
    
    def epoch_end(self, epoch, result):
        print("Epoch [{}], loss: {:.4f}, acc: {:.4f}".format(epoch, result['loss'], result['acc']))



class CIFAR10Model(ImageClassificationBase):
    def __init__(self, InputSize, OutputSize):
        """
        Inputs: 
        InputSize - Size of the Input
        OutputSize - Size of the Output
        """
        #############################
        # Fill your network initialization of choice here!
        #############################
        super().__init__()
        self.network = nn.Sequential(
            nn.Conv2d(3, 32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2), # output: 64 x 16 x 16
            nn.BatchNorm2d(64),

            nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.Conv2d(128, 128, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2), # output: 128 x 8 x 8
            nn.BatchNorm2d(128),

            nn.Conv2d(128, 256, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.Conv2d(256, 256, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2), # output: 256 x 4 x 4
            nn.BatchNorm2d(256),

            nn.Flatten(), 
            nn.Linear(256*4*4, 1024),
            nn.ReLU(),
            nn.Linear(1024, 512),
            nn.ReLU(),
            nn.Linear(512, 10))
        
    def forward(self, xb):
        """
        Input:
        xb is a MiniBatch of the current image
        Outputs:
        out - output of the network
        """
        #############################
        # Fill your network structure of choice here!
        #############################
        return self.network(xb)


In [6]:
import time
import glob
import os
import sys
import matplotlib.pyplot as plt
import numpy as np

def tic():
    """
    Function to start timer
    Tries to mimic tic() toc() in MATLAB
    """
    StartTime = time.time()
    return StartTime

def toc(StartTime):
    """
    Function to stop timer
    Tries to mimic tic() toc() in MATLAB
    """
    return time.time() - StartTime

def FindLatestModel(CheckPointPath):
    """
    Finds Latest Model in CheckPointPath
    Inputs:
    CheckPointPath - Path where you have stored checkpoints
    Outputs:
    LatestFile - File Name of the latest checkpoint
    """
    FileList = glob.glob(CheckPointPath + '*.ckpt.index') # * means all if need specific format then *.csv
    LatestFile = max(FileList, key=os.path.getctime)
    # Strip everything else except needed information
    LatestFile = LatestFile.replace(CheckPointPath, '')
    LatestFile = LatestFile.replace('.ckpt.index', '')
    return LatestFile


def convertToOneHot(vector, NumClasses):
    """
    Inputs:
    vector - vector of argmax indexes
    NumClasses - Number of classes
    """
    return np.equal.outer(vector, np.arange(NumClasses)).astype(np.float)

### Train your neural network

In [7]:
# # calculating 3 channel mean and std for image dataset
# import tqdm
# import random

# means = np.array([0, 0, 0], dtype=np.float32)
# stds = np.array([0, 0, 0], dtype=np.float32)
# total_images = 0
# randomly_sample = 5000
# for f in tqdm.tqdm(random.sample(glob.glob("dataset_path/**.jpg", recursive = True), randomly_sample)):
#     img = cv2.imread(f)
#     means += img.mean(axis=(0,1))
#     stds += img.std(axis=(0,1))
#     total_images += 1
# means = means / (total_images * 255.)
# stds = stds / (total_images * 255.)
# print("Total images: ", total_images)
# print("Means: ", means)
# print("Stds: ", stds)

In [11]:
import torch
import torchvision
from torch.utils.tensorboard import SummaryWriter
from torchvision import datasets, transforms
from torch.optim import AdamW
from torchvision.datasets import CIFAR10
import cv2
import sys
import os
import numpy as np
import random
import skimage
import PIL
import os
import glob
import random
from skimage import data, exposure, img_as_float
import matplotlib.pyplot as plt
import numpy as np
import time
from torchvision.transforms import ToTensor
import argparse
import shutil
import string
from termcolor import colored, cprint
import math as m
from tqdm.notebook import tqdm

def SetupAll(CheckPointPath):
    """
    Inputs: 
    CheckPointPath - Path to save checkpoints/model
    Outputs:
    SaveCheckPoint - Save checkpoint every SaveCheckPoint iteration in every epoch, checkpoint saved automatically after every epoch
    ImageSize - Size of the image
    NumTrainSamples - length(Train)
    TrainLabels - Labels corresponding to Train
    NumClasses - Number of classes
    """
    # Read and Setup Labels
    LabelsPathTrain = 'TxtFiles/LabelsTrain.txt'
    TrainLabels = ReadLabels(LabelsPathTrain)

    # If CheckPointPath doesn't exist make the path
    if(not (os.path.isdir(CheckPointPath))):
        os.makedirs(CheckPointPath)
        
    # Save checkpoint every SaveCheckPoint iteration in every epoch, checkpoint saved automatically after every epoch
    SaveCheckPoint = 100 
    
    # Image Input Shape
    ImageSize = [32, 32, 3]
    NumTrainSamples = len(TrainSet)

    # Number of classes
    NumClasses = 10

    return SaveCheckPoint, ImageSize, NumTrainSamples, TrainLabels, NumClasses


def ReadLabels(LabelsPathTrain):
    if(not (os.path.isfile(LabelsPathTrain))):
        print('ERROR: Train Labels do not exist in '+LabelsPathTrain)
        sys.exit()
    else:
        TrainLabels = open(LabelsPathTrain, 'r')
        TrainLabels = TrainLabels.read()
        TrainLabels = map(float, TrainLabels.split())

    return TrainLabels
    

def ReadDirNames(ReadPath):
    """
    Inputs: 
    ReadPath is the path of the file you want to read
    Outputs:
    DirNames is the data loaded from TxtFiles/DirNames.txt which has full path to all image files without extension
    """
    # Read text files
    DirNames = open(ReadPath, 'r')
    DirNames = DirNames.read()
    DirNames = DirNames.split()
    return DirNames

    
def GenerateBatch(TrainSet, TrainLabels, ImageSize, MiniBatchSize, Indices):
    """
    Inputs: 
    TrainSet - Variable with Subfolder paths to train files
    NOTE that Train can be replaced by Val/Test for generating batch corresponding to validation (held-out testing in this case)/testing
    TrainLabels - Labels corresponding to Train
    NOTE that TrainLabels can be replaced by Val/TestLabels for generating batch corresponding to validation (held-out testing in this case)/testing
    ImageSize is the Size of the Image
    MiniBatchSize is the size of the MiniBatch
   
    Outputs:
    I1Batch - Batch of images
    LabelBatch - Batch of one-hot encoded labels 
    """
    I1Batch = []
    LabelBatch = []
    
    ImageNum = 0
    while ImageNum < MiniBatchSize:
        # Generate random image
        RandIdx = random.randint(0, len(Indices)-1)
        
        ImageNum += 1

        ##########################################################
        # Add any standardization or data augmentation here!
        ##########################################################

        I1, Label = TrainSet[Indices[RandIdx]]

        # Append All Images and Mask
        I1Batch.append(I1)
        LabelBatch.append(torch.tensor(Label))
        
    return torch.stack(I1Batch), torch.stack(LabelBatch)


def PrettyPrint(NumEpochs, DivTrain, MiniBatchSize, NumTrainSamples, LatestFile):
    """
    Prints all stats with all arguments
    """
    print('Number of Epochs Training will run for ' + str(NumEpochs))
    print('Factor of reduction in training data is ' + str(DivTrain))
    print('Mini Batch Size ' + str(MiniBatchSize))
    print('Number of Training Images ' + str(NumTrainSamples))
    if LatestFile is not None:
        print('Loading latest checkpoint with the name ' + LatestFile)              

def TrainOperation(TrainLabels, NumTrainSamples, ImageSize,
                   NumEpochs, MiniBatchSize, SaveCheckPoint, CheckPointPath,
                   DivTrain, LatestFile, TrainSet, LogsPath, TrainIndices, ValIndices):
    """
    Inputs: 
    TrainLabels - Labels corresponding to Train/Test
    NumTrainSamples - length(Train)
    ImageSize - Size of the image
    NumEpochs - Number of passes through the Train data
    MiniBatchSize is the size of the MiniBatch
    SaveCheckPoint - Save checkpoint every SaveCheckPoint iteration in every epoch, checkpoint saved automatically after every epoch
    CheckPointPath - Path to save checkpoints/model
    DivTrain - Divide the data by this number for Epoch calculation, use if you have a lot of dataor for debugging code
    LatestFile - Latest checkpointfile to continue training
    TrainSet - The training dataset
    LogsPath - Path to save Tensorboard Logs
    Outputs:
    Saves Trained network in CheckPointPath and Logs to LogsPath
    """
    # Initialize the model
    model = CIFAR10Model(InputSize=3*32*32,OutputSize=10) 
    ###############################################
    # Fill your optimizer of choice here!
    ###############################################
    Optimizer = torch.optim.Adam(model.parameters(), lr=0.001,weight_decay=0.0005)

    # Tensorboard
    # Create a summary to monitor loss tensor
    Writer = SummaryWriter(LogsPath)

    if LatestFile is not None:
        CheckPoint = torch.load(CheckPointPath + LatestFile + '.ckpt')
        # Extract only numbers from the name
        StartEpoch = int(''.join(c for c in LatestFile.split('a')[0] if c.isdigit()))
        model.load_state_dict(CheckPoint['model_state_dict'])
        print('Loaded latest checkpoint with the name ' + LatestFile + '....')
    else:
        StartEpoch = 0
        print('New model initialized....')
        
    history = []
    for Epochs in tqdm(range(StartEpoch, NumEpochs)):
        TrainLosses = []
        
        NumIterationsPerEpoch = int(NumTrainSamples/MiniBatchSize/DivTrain)
        for PerEpochCounter in tqdm(range(NumIterationsPerEpoch)):
            TrainBatch = GenerateBatch(TrainSet, TrainLabels, ImageSize, MiniBatchSize, TrainIndices)
            
            # Predict output with forward pass
            LossThisBatch = model.training_step(TrainBatch)
            TrainLosses.append(LossThisBatch)
            
            Optimizer.zero_grad()
            LossThisBatch.backward()
            Optimizer.step()
            
            # Save checkpoint every some SaveCheckPoint's iterations
            if PerEpochCounter % SaveCheckPoint == 0:
                # Save the Model learnt in this epoch
                SaveName =  CheckPointPath + str(Epochs) + 'a' + str(PerEpochCounter) + 'model.ckpt'
                
                torch.save({'epoch': Epochs,'model_state_dict': model.state_dict(),'optimizer_state_dict': Optimizer.state_dict(),'loss': LossThisBatch}, SaveName)
                print('\n' + SaveName + ' Model Saved...')

            result = model.validation_step(TrainBatch)
            result['TrainLoss'] = torch.stack(TrainLosses).mean().item()
            model.epoch_end(Epochs*NumIterationsPerEpoch + PerEpochCounter, result)
            history.append(result)
            
            # Tensorboard
            Writer.add_scalar('LossEveryIter', result["loss"], Epochs*NumIterationsPerEpoch + PerEpochCounter)
            Writer.add_scalar('Accuracy', result["acc"], Epochs*NumIterationsPerEpoch + PerEpochCounter)
            # If you don't flush the tensorboard doesn't update until a lot of iterations!
            Writer.flush()

        ValBatch = GenerateBatch(TrainSet, TrainLabels, ImageSize, MiniBatchSize, ValIndices)
        ValResult = model.validation_step(ValBatch)
        Writer.add_scalar('ValidationLossEveryEpoch',ValResult['loss'],Epochs)
        Writer.add_scalar('ValidationAccuracyEveryEpoch',ValResult['acc'],Epochs)
        Writer.flush()
        
        # Save model every epoch
        SaveName = CheckPointPath + str(Epochs) + 'model.ckpt'
        torch.save({'epoch': Epochs,'model_state_dict': model.state_dict(),'optimizer_state_dict': Optimizer.state_dict(),'loss': LossThisBatch}, SaveName)
        print('\n' + SaveName + ' Model Saved...')
        


# Default Hyperparameters
NumEpochs = 10

normalize = torchvision.transforms.Normalize(mean=[0.4914, 0.4822, 0.4465],
                                             std=[0.2470, 0.2435, 0.2616])

# transforms_to_apply = transforms.Compose([transforms.Resize((64,64)),transforms.ToTensor(),normalize])
transformations = transforms.Compose([transforms.ToTensor(), normalize])
TrainSet = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transformations)
ValSet = torchvision.datasets.CIFAR10(root='../../data', train=True,
                                        download=True, transform=transformations)

valid_size = 0.1
num_train = len(TrainSet)
indices = list (range(num_train))
split = int(np.floor(valid_size * num_train))

np.random.seed(42)
np.random.shuffle(indices)

TrainIndices, ValIndices = indices[split:], indices[:split]


DivTrain = 1.0
MiniBatchSize = 1024
LoadCheckPoint = 0
CheckPointPath = "Checkpoints/"
LogsPath = "Logs"

# Setup all needed paraymeters including file reading
SaveCheckPoint, ImageSize, NumTrainSamples, TrainLabels, NumClasses = SetupAll(CheckPointPath)

# Find Latest Checkpoint File
if LoadCheckPoint==1:
    LatestFile = FindLatestModel(CheckPointPath)
else:
    LatestFile = None

# Pretty print stats
PrettyPrint(NumEpochs, DivTrain, MiniBatchSize, NumTrainSamples, LatestFile)

TrainOperation(TrainLabels, NumTrainSamples, ImageSize,
                NumEpochs, MiniBatchSize, SaveCheckPoint, CheckPointPath,
                DivTrain, LatestFile, TrainSet, LogsPath, TrainIndices, ValIndices)

Files already downloaded and verified
Files already downloaded and verified
Number of Epochs Training will run for 10
Factor of reduction in training data is 1.0
Mini Batch Size 1024
Number of Training Images 50000
New model initialized....


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/0a0model.ckpt Model Saved...
Epoch [0], loss: 2.0006, acc: 0.2891
Epoch [1], loss: 2.0899, acc: 0.2695
Epoch [2], loss: 2.0720, acc: 0.3027
Epoch [3], loss: 1.9465, acc: 0.3037
Epoch [4], loss: 1.8002, acc: 0.3623
Epoch [5], loss: 1.6991, acc: 0.3867
Epoch [6], loss: 1.7010, acc: 0.3691
Epoch [7], loss: 1.6043, acc: 0.4219
Epoch [8], loss: 1.5624, acc: 0.4268
Epoch [9], loss: 1.4624, acc: 0.4541
Epoch [10], loss: 1.4843, acc: 0.4521
Epoch [11], loss: 1.4453, acc: 0.4512
Epoch [12], loss: 1.4314, acc: 0.4785
Epoch [13], loss: 1.3687, acc: 0.4980
Epoch [14], loss: 1.3319, acc: 0.5098
Epoch [15], loss: 1.3625, acc: 0.4912
Epoch [16], loss: 1.2963, acc: 0.5283
Epoch [17], loss: 1.2314, acc: 0.5479
Epoch [18], loss: 1.3337, acc: 0.5137
Epoch [19], loss: 1.2894, acc: 0.5303
Epoch [20], loss: 1.2866, acc: 0.5254
Epoch [21], loss: 1.2443, acc: 0.5332
Epoch [22], loss: 1.1872, acc: 0.5664
Epoch [23], loss: 1.1744, acc: 0.5723
Epoch [24], loss: 1.2405, acc: 0.5479
Epoch [25], loss: 

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/1a0model.ckpt Model Saved...
Epoch [48], loss: 0.8555, acc: 0.6943
Epoch [49], loss: 0.7675, acc: 0.7275
Epoch [50], loss: 0.8056, acc: 0.7090
Epoch [51], loss: 0.7869, acc: 0.7227
Epoch [52], loss: 0.7705, acc: 0.7324
Epoch [53], loss: 0.8251, acc: 0.7109
Epoch [54], loss: 0.8234, acc: 0.6992
Epoch [55], loss: 0.7506, acc: 0.7295
Epoch [56], loss: 0.7158, acc: 0.7441
Epoch [57], loss: 0.7565, acc: 0.7334
Epoch [58], loss: 0.7176, acc: 0.7490
Epoch [59], loss: 0.7276, acc: 0.7568
Epoch [60], loss: 0.7081, acc: 0.7598
Epoch [61], loss: 0.7270, acc: 0.7471
Epoch [62], loss: 0.7141, acc: 0.7529
Epoch [63], loss: 0.6680, acc: 0.7686
Epoch [64], loss: 0.6964, acc: 0.7646
Epoch [65], loss: 0.6672, acc: 0.7588
Epoch [66], loss: 0.6737, acc: 0.7803
Epoch [67], loss: 0.6554, acc: 0.7764
Epoch [68], loss: 0.6195, acc: 0.7783
Epoch [69], loss: 0.6591, acc: 0.7715
Epoch [70], loss: 0.6359, acc: 0.7832
Epoch [71], loss: 0.6235, acc: 0.8008
Epoch [72], loss: 0.5990, acc: 0.7969
Epoch [7

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/2a0model.ckpt Model Saved...
Epoch [96], loss: 0.4631, acc: 0.8428
Epoch [97], loss: 0.4535, acc: 0.8613
Epoch [98], loss: 0.3989, acc: 0.8877
Epoch [99], loss: 0.4516, acc: 0.8516
Epoch [100], loss: 0.4300, acc: 0.8652
Epoch [101], loss: 0.4287, acc: 0.8662
Epoch [102], loss: 0.4592, acc: 0.8584
Epoch [103], loss: 0.4329, acc: 0.8555
Epoch [104], loss: 0.4116, acc: 0.8633
Epoch [105], loss: 0.4370, acc: 0.8574
Epoch [106], loss: 0.4565, acc: 0.8525
Epoch [107], loss: 0.4072, acc: 0.8623
Epoch [108], loss: 0.3949, acc: 0.8770
Epoch [109], loss: 0.4080, acc: 0.8779
Epoch [110], loss: 0.4219, acc: 0.8604
Epoch [111], loss: 0.4433, acc: 0.8545
Epoch [112], loss: 0.4151, acc: 0.8711
Epoch [113], loss: 0.3670, acc: 0.8818
Epoch [114], loss: 0.3697, acc: 0.8828
Epoch [115], loss: 0.3716, acc: 0.8838
Epoch [116], loss: 0.3785, acc: 0.8818
Epoch [117], loss: 0.3800, acc: 0.8838
Epoch [118], loss: 0.3893, acc: 0.8682
Epoch [119], loss: 0.3691, acc: 0.8828
Epoch [120], loss: 0.3251,

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/3a0model.ckpt Model Saved...
Epoch [144], loss: 0.2669, acc: 0.9199
Epoch [145], loss: 0.2457, acc: 0.9209
Epoch [146], loss: 0.2628, acc: 0.9355
Epoch [147], loss: 0.2081, acc: 0.9453
Epoch [148], loss: 0.2401, acc: 0.9326
Epoch [149], loss: 0.2643, acc: 0.9258
Epoch [150], loss: 0.2158, acc: 0.9434
Epoch [151], loss: 0.2386, acc: 0.9355
Epoch [152], loss: 0.2075, acc: 0.9414
Epoch [153], loss: 0.2154, acc: 0.9395
Epoch [154], loss: 0.2147, acc: 0.9258
Epoch [155], loss: 0.2148, acc: 0.9385
Epoch [156], loss: 0.2243, acc: 0.9424
Epoch [157], loss: 0.2108, acc: 0.9355
Epoch [158], loss: 0.2333, acc: 0.9355
Epoch [159], loss: 0.2031, acc: 0.9365
Epoch [160], loss: 0.2301, acc: 0.9414
Epoch [161], loss: 0.2036, acc: 0.9492
Epoch [162], loss: 0.1920, acc: 0.9473
Epoch [163], loss: 0.2068, acc: 0.9375
Epoch [164], loss: 0.2215, acc: 0.9268
Epoch [165], loss: 0.1982, acc: 0.9453
Epoch [166], loss: 0.2210, acc: 0.9414
Epoch [167], loss: 0.2154, acc: 0.9453
Epoch [168], loss: 0.1

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/4a0model.ckpt Model Saved...
Epoch [192], loss: 0.1821, acc: 0.9600
Epoch [193], loss: 0.1757, acc: 0.9541
Epoch [194], loss: 0.1636, acc: 0.9551
Epoch [195], loss: 0.1501, acc: 0.9609
Epoch [196], loss: 0.1757, acc: 0.9590
Epoch [197], loss: 0.1288, acc: 0.9707
Epoch [198], loss: 0.1686, acc: 0.9492
Epoch [199], loss: 0.1439, acc: 0.9658
Epoch [200], loss: 0.1466, acc: 0.9658
Epoch [201], loss: 0.1401, acc: 0.9648
Epoch [202], loss: 0.1328, acc: 0.9678
Epoch [203], loss: 0.1195, acc: 0.9668
Epoch [204], loss: 0.1372, acc: 0.9648
Epoch [205], loss: 0.1485, acc: 0.9658
Epoch [206], loss: 0.1211, acc: 0.9639
Epoch [207], loss: 0.1330, acc: 0.9746
Epoch [208], loss: 0.1427, acc: 0.9648
Epoch [209], loss: 0.1204, acc: 0.9756
Epoch [210], loss: 0.1272, acc: 0.9648
Epoch [211], loss: 0.1384, acc: 0.9736
Epoch [212], loss: 0.1330, acc: 0.9668
Epoch [213], loss: 0.1109, acc: 0.9805
Epoch [214], loss: 0.1504, acc: 0.9639
Epoch [215], loss: 0.1105, acc: 0.9766
Epoch [216], loss: 0.1

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/5a0model.ckpt Model Saved...
Epoch [240], loss: 0.0919, acc: 0.9863
Epoch [241], loss: 0.0796, acc: 0.9854
Epoch [242], loss: 0.0905, acc: 0.9834
Epoch [243], loss: 0.0883, acc: 0.9814
Epoch [244], loss: 0.0741, acc: 0.9844
Epoch [245], loss: 0.0833, acc: 0.9834
Epoch [246], loss: 0.0726, acc: 0.9883
Epoch [247], loss: 0.0733, acc: 0.9873
Epoch [248], loss: 0.0803, acc: 0.9834
Epoch [249], loss: 0.0710, acc: 0.9873
Epoch [250], loss: 0.0863, acc: 0.9785
Epoch [251], loss: 0.0757, acc: 0.9893
Epoch [252], loss: 0.0707, acc: 0.9883
Epoch [253], loss: 0.0808, acc: 0.9863
Epoch [254], loss: 0.0678, acc: 0.9844
Epoch [255], loss: 0.0663, acc: 0.9863
Epoch [256], loss: 0.0681, acc: 0.9883
Epoch [257], loss: 0.0738, acc: 0.9873
Epoch [258], loss: 0.0628, acc: 0.9902
Epoch [259], loss: 0.0575, acc: 0.9902
Epoch [260], loss: 0.0625, acc: 0.9902
Epoch [261], loss: 0.0721, acc: 0.9834
Epoch [262], loss: 0.0604, acc: 0.9932
Epoch [263], loss: 0.0741, acc: 0.9873
Epoch [264], loss: 0.0

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/6a0model.ckpt Model Saved...
Epoch [288], loss: 0.0492, acc: 0.9941
Epoch [289], loss: 0.0626, acc: 0.9854
Epoch [290], loss: 0.0594, acc: 0.9893
Epoch [291], loss: 0.0646, acc: 0.9863
Epoch [292], loss: 0.0518, acc: 0.9941
Epoch [293], loss: 0.0591, acc: 0.9883
Epoch [294], loss: 0.0476, acc: 0.9932
Epoch [295], loss: 0.0548, acc: 0.9883
Epoch [296], loss: 0.0619, acc: 0.9922
Epoch [297], loss: 0.0537, acc: 0.9941
Epoch [298], loss: 0.0523, acc: 0.9912
Epoch [299], loss: 0.0567, acc: 0.9893
Epoch [300], loss: 0.0525, acc: 0.9902
Epoch [301], loss: 0.0565, acc: 0.9912
Epoch [302], loss: 0.0499, acc: 0.9951
Epoch [303], loss: 0.0480, acc: 0.9932
Epoch [304], loss: 0.0525, acc: 0.9893
Epoch [305], loss: 0.0494, acc: 0.9883
Epoch [306], loss: 0.0502, acc: 0.9932
Epoch [307], loss: 0.0483, acc: 0.9922
Epoch [308], loss: 0.0530, acc: 0.9922
Epoch [309], loss: 0.0486, acc: 0.9912
Epoch [310], loss: 0.0558, acc: 0.9912
Epoch [311], loss: 0.0554, acc: 0.9883
Epoch [312], loss: 0.0

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/7a0model.ckpt Model Saved...
Epoch [336], loss: 0.0417, acc: 0.9932
Epoch [337], loss: 0.0279, acc: 0.9990
Epoch [338], loss: 0.0374, acc: 0.9951
Epoch [339], loss: 0.0356, acc: 0.9951
Epoch [340], loss: 0.0287, acc: 0.9980
Epoch [341], loss: 0.0329, acc: 0.9980
Epoch [342], loss: 0.0365, acc: 0.9961
Epoch [343], loss: 0.0296, acc: 0.9980
Epoch [344], loss: 0.0340, acc: 0.9980
Epoch [345], loss: 0.0357, acc: 0.9961
Epoch [346], loss: 0.0333, acc: 0.9980
Epoch [347], loss: 0.0323, acc: 0.9971
Epoch [348], loss: 0.0470, acc: 0.9932
Epoch [349], loss: 0.0352, acc: 0.9961
Epoch [350], loss: 0.0349, acc: 0.9971
Epoch [351], loss: 0.0240, acc: 0.9990
Epoch [352], loss: 0.0356, acc: 0.9951
Epoch [353], loss: 0.0317, acc: 0.9951
Epoch [354], loss: 0.0352, acc: 0.9951
Epoch [355], loss: 0.0265, acc: 0.9990
Epoch [356], loss: 0.0337, acc: 0.9951
Epoch [357], loss: 0.0349, acc: 0.9971
Epoch [358], loss: 0.0250, acc: 0.9990
Epoch [359], loss: 0.0359, acc: 0.9951
Epoch [360], loss: 0.0

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/8a0model.ckpt Model Saved...
Epoch [384], loss: 0.0320, acc: 0.9951
Epoch [385], loss: 0.0246, acc: 0.9980
Epoch [386], loss: 0.0407, acc: 0.9932
Epoch [387], loss: 0.0355, acc: 0.9961
Epoch [388], loss: 0.0306, acc: 0.9961
Epoch [389], loss: 0.0248, acc: 0.9990
Epoch [390], loss: 0.0331, acc: 0.9951
Epoch [391], loss: 0.0258, acc: 0.9980
Epoch [392], loss: 0.0313, acc: 0.9951
Epoch [393], loss: 0.0306, acc: 0.9980
Epoch [394], loss: 0.0374, acc: 0.9941
Epoch [395], loss: 0.0310, acc: 0.9971
Epoch [396], loss: 0.0277, acc: 0.9961
Epoch [397], loss: 0.0271, acc: 0.9971
Epoch [398], loss: 0.0307, acc: 0.9971
Epoch [399], loss: 0.0376, acc: 0.9951
Epoch [400], loss: 0.0263, acc: 0.9990
Epoch [401], loss: 0.0298, acc: 0.9990
Epoch [402], loss: 0.0249, acc: 0.9980
Epoch [403], loss: 0.0271, acc: 0.9971
Epoch [404], loss: 0.0357, acc: 0.9961
Epoch [405], loss: 0.0263, acc: 0.9971
Epoch [406], loss: 0.0218, acc: 0.9980
Epoch [407], loss: 0.0286, acc: 0.9961
Epoch [408], loss: 0.0

  0%|          | 0/48 [00:00<?, ?it/s]


Checkpoints/9a0model.ckpt Model Saved...
Epoch [432], loss: 0.0217, acc: 0.9980
Epoch [433], loss: 0.0213, acc: 0.9961
Epoch [434], loss: 0.0208, acc: 0.9990
Epoch [435], loss: 0.0241, acc: 0.9971
Epoch [436], loss: 0.0231, acc: 0.9980
Epoch [437], loss: 0.0229, acc: 0.9971
Epoch [438], loss: 0.0217, acc: 0.9990
Epoch [439], loss: 0.0201, acc: 0.9980
Epoch [440], loss: 0.0225, acc: 0.9971
Epoch [441], loss: 0.0263, acc: 0.9971
Epoch [442], loss: 0.0267, acc: 0.9971
Epoch [443], loss: 0.0240, acc: 0.9971
Epoch [444], loss: 0.0170, acc: 1.0000
Epoch [445], loss: 0.0225, acc: 0.9961
Epoch [446], loss: 0.0237, acc: 0.9951
Epoch [447], loss: 0.0247, acc: 0.9971
Epoch [448], loss: 0.0231, acc: 0.9990
Epoch [449], loss: 0.0172, acc: 0.9990
Epoch [450], loss: 0.0217, acc: 1.0000
Epoch [451], loss: 0.0261, acc: 0.9961
Epoch [452], loss: 0.0194, acc: 0.9990
Epoch [453], loss: 0.0240, acc: 0.9980
Epoch [454], loss: 0.0217, acc: 0.9980
Epoch [455], loss: 0.0201, acc: 0.9990
Epoch [456], loss: 0.0

### Test your neural network

In [10]:
import cv2
import os
import sys
import glob
import random
from skimage import data, exposure, img_as_float
import matplotlib.pyplot as plt
import numpy as np
import time
from torchvision.transforms import ToTensor
import argparse
import shutil
import string
import math as m
from sklearn.metrics import confusion_matrix
from tqdm.notebook import tqdm
import torch

def SetupAll():
    """
    Outputs:
    ImageSize - Size of the Image
    """   
    # Image Input Shape
    ImageSize = [32, 32, 3]

    return ImageSize

def StandardizeInputs(Img):
    ##########################################################################
    # Add any standardization or cropping/resizing if used in Training here!
    ##########################################################################
    return Img
    
def ReadImages(Img):
    """
    Outputs:
    I1Combined - I1 image after any standardization and/or cropping/resizing to ImageSize
    I1 - Original I1 image for visualization purposes only
    """    
    I1 = Img
    
    if(I1 is None):
        # OpenCV returns empty list if image is not read! 
        print('ERROR: Image I1 cannot be read')
        sys.exit()
        
    I1S = StandardizeInputs(np.float32(I1))

    I1Combined = np.expand_dims(I1S, axis=0)

    return I1Combined, I1
                

def TestOperation(ImageSize, ModelPath, TestSet, LabelsPathPred):
    """
    Inputs: 
    ImageSize is the size of the image
    ModelPath - Path to load trained model from
    TestSet - The test dataset
    LabelsPathPred - Path to save predictions
    Outputs:
    Predictions written to TxtFiles/PredOut.txt
    """
    # Predict output with forward pass, MiniBatchSize for Test is 1
    model = CIFAR10Model(InputSize=3*32*32,OutputSize=10) 
    
    CheckPoint = torch.load(ModelPath)
    model.load_state_dict(CheckPoint['model_state_dict'])
    print('Number of parameters in this model are %d ' % len(model.state_dict().items()))
    
    OutSaveT = open(LabelsPathPred, 'w')

    for count in tqdm(range(len(TestSet))): 
        Img, Label = TestSet[count]
        Img, ImgOrg = ReadImages(Img)
        PredT = torch.argmax(model(torch.tensor(Img))).item()

        OutSaveT.write(str(PredT)+'\n')
    OutSaveT.close()

def Accuracy(Pred, GT):
    """
    Inputs: 
    Pred are the predicted labels
    GT are the ground truth labels
    Outputs:
    Accuracy in percentage
    """
    return (np.sum(np.array(Pred)==np.array(GT))*100.0/len(Pred))

def ReadLabels(LabelsPathTest, LabelsPathPred):
    if(not (os.path.isfile(LabelsPathTest))):
        print('ERROR: Test Labels do not exist in '+LabelsPathTest)
        sys.exit()
    else:
        LabelTest = open(LabelsPathTest, 'r')
        LabelTest = LabelTest.read()
        LabelTest = map(float, LabelTest.split())

    if(not (os.path.isfile(LabelsPathPred))):
        print('ERROR: Pred Labels do not exist in '+LabelsPathPred)
        sys.exit()
    else:
        LabelPred = open(LabelsPathPred, 'r')
        LabelPred = LabelPred.read()
        LabelPred = map(float, LabelPred.split())
        
    return LabelTest, LabelPred

def ConfusionMatrix(LabelsTrue, LabelsPred):
    """
    LabelsTrue - True labels
    LabelsPred - Predicted labels
    """

    # Get the confusion matrix using sklearn.
    LabelsTrue, LabelsPred = list(LabelsTrue), list(LabelsPred)
    cm = confusion_matrix(y_true=LabelsTrue,  # True class for test-set.
                          y_pred=LabelsPred)  # Predicted class.

    # Print the confusion matrix as text.
    for i in range(10):
        print(str(cm[i, :]) + ' ({0})'.format(i))

    # Print the class-numbers for easy reference.
    class_numbers = [" ({0})".format(i) for i in range(10)]
    print("".join(class_numbers))

    print('Accuracy: '+ str(Accuracy(LabelsPred, LabelsTrue)), '%')


ModelPath = "final_models/P2_TunedNetwork/9model.ckpt"
LabelsPath = "TxtFiles/LabelsTest.txt"

TestSet = CIFAR10(root='data/', train=False, transform=transformations)

# Setup all needed parameters including file reading
ImageSize = SetupAll()

# Define PlaceHolder variables for Input and Predicted output
LabelsPathPred = 'TxtFiles/PredOut.txt' # Path to save predicted labels

TestOperation(ImageSize, ModelPath, TestSet, LabelsPathPred)

# Plot Confusion Matrix
LabelsTrue, LabelsPred = ReadLabels(LabelsPath, LabelsPathPred)
ConfusionMatrix(LabelsTrue, LabelsPred) 

Number of parameters in this model are 33 


  0%|          | 0/10000 [00:00<?, ?it/s]

[623  35  52  74  58  28  33   8  29  60] (0)
[ 15 840   8  14   8   2  22  15  20  56] (1)
[ 82  17 480 117  57  83  56  65  12  31] (2)
[ 44  18  46 505  55 142  85  46  23  36] (3)
[ 70   5  82  87 521  89  34  90   9  13] (4)
[ 30  11  71 128  44 536  70  77  10  23] (5)
[ 40  52  50 155  45  69 498  34  15  42] (6)
[ 35   9  32  38  44  73  12 724   5  28] (7)
[ 65  78  20  67  18  24  47  13 590  78] (8)
[ 39 117   8  34   7  16  33  12  10 724] (9)
 (0) (1) (2) (3) (4) (5) (6) (7) (8) (9)
Accuracy: 60.41 %
